interface DropDownfieldsType {
  label: string;
  value: string;
}

export const countriesPhoneCode: Array<DropDownfieldsType> = [
  { label: 'Austria', value: '+43' },
  { label: 'Azerbaijan', value: '+994' },
  { label: 'Bahamas', value: '+1242' },
  { label: 'Bahrain', value: '+973' },
  { label: 'Bangladesh', value: '+880' },
  { label: 'Barbados', value: '+1246' },
  { label: 'Barbuda', value: '+1268' },
  { label: 'Belarus', value: '+375' },
  { label: 'Belgium', value: '+32' },
  { label: 'Belize', value: '+501' },
  { label: 'Benin', value: '+229' },
  { label: 'Bermuda', value: '+1441' },
  { label: 'Bhutan', value: '+975' },
  { label: 'Bolivia', value: '+591' },
  { label: 'Bonaire', value: '+5997' },
  { label: 'Bosnia and Herzegovina', value: '+387' },
  { label: 'Botswana', value: '+267' },
  { label: 'Brazil', value: '+55' },
  { label: 'British Indian Ocean Territory', value: '+246' },
  { label: 'British Virgin Islands', value: '+1284' },
  { label: 'Brunei Darussalam', value: '+673' },
  { label: 'Bulgaria', value: '+359' },
  { label: 'Burkina Faso', value: '+226' },
  { label: 'Burundi', value: '+257' },
  { label: 'Cambodia', value: '+855' },
  { label: 'Cameroon', value: '+237' },
  { label: 'Canada', value: '+1' },
  { label: 'Cape Verde', value: '+238' },
  { label: 'Caribbean Netherlands', value: '+599 3' },
  { label: 'Cayman Islands', value: '+1 345' },
  { label: 'Central African Republic', value: '+236' },
  { label: 'Chad', value: '+235' },
  { label: 'Chatham Island, New Zealand', value: '+64' },
  { label: 'Chile', value: '+56' },
  { label: 'China', value: '+86' },
  { label: 'Christmas Island', value: '+61 89164' },
  { label: 'Cocos (Keeling) Islands', value: '+61 89162' },
  { label: 'Colombia', value: '+57' },
  { label: 'Comoros', value: '+269' },
  { label: 'Congo', value: '+242' },
  { label: 'Congo, the Democratic Republic of the (Zaire)', value: '+243' },
  { label: 'Cook Islands', value: '+682' },
  { label: 'Costa Rica', value: '+506' },
  { label: 'Ivory Coast', value: '+225' },
  { label: 'Croatia', value: '+385' },
  { label: 'Cuba', value: '+53' },
  { label: 'Guantanamo Bay, Cuba', value: '+5399' },
  { label: 'Curaçao', value: '+5999' },
  { label: 'Cyprus', value: '+357' },
  { label: 'Czech Republic', value: '+420' },
  { label: 'Denmark', value: '+45' },
  { label: 'Diego Garcia', value: '+246' },
  { label: 'Djibouti', value: '+253' },
  { label: 'Dominica', value: '+1 767' },
  { label: 'Dominican Republic', value: '+1 809' },
  { label: 'East Timor', value: '+670' },
  { label: 'Easter Island', value: '+56' },
  { label: 'Ecuador', value: '+593' },
  { label: 'Egypt', value: '+20' },
  { label: 'El Salvador', value: '+503' },
  { label: 'Ellipso (Mobile Satellite service)', value: '+8812' },
  { label: 'EMSAT (Mobile Satellite service)', value: '+88213' },
  { label: 'Equatorial Guinea', value: '+240' },
  { label: 'Eritrea', value: '+291' },
  { label: 'Estonia', value: '+372' },
  { label: 'Ethiopia', value: '+251' },
  { label: 'Falkland Islands', value: '+500' },
  { label: 'Faroe Islands', value: '+298' },
  { label: 'Fiji', value: '+679' },
  { label: 'Finland', value: '+358' },
  { label: 'France', value: '+33' },
  { label: 'French Antilles', value: '+596' },
  { label: 'French Guiana', value: '+594' },
  { label: 'French Polynesia', value: '+689' },
  { label: 'Gabon', value: '+241' },
  { label: 'Gambia', value: '+220' },
  { label: 'Georgia', value: '+995' },
  { label: 'Germany', value: '+49' },
  { label: 'Ghana', value: '+233' },
  { label: 'Gibraltar', value: '+350' },
  { label: 'Global Mobile Satellite System (GMSS)', value: '+881' },
  { label: 'Globalstar (Mobile Satellite Service)', value: '+881 8' },
  { label: 'Greece', value: '+30' },
  { label: 'Greenland', value: '+299' },
  { label: 'Grenada', value: '+1 473' },
  { label: 'Guadeloupe', value: '+590' },
  { label: 'Guam', value: '+1 671' },
  { label: 'Guatemala', value: '+502' },
  { label: 'Guernsey', value: '+44 1481' },
  { label: 'Guinea', value: '+224' },
  { label: 'Guinea-Bissau', value: '+245' },
  { label: 'Guyana', value: '+592' },
  { label: 'Haiti', value: '+509' },
  { label: 'Honduras', value: '+504' },
  { label: 'Hong Kong', value: '+852' },
  { label: 'Hungary', value: '+36' },
  { label: 'Iceland', value: '+354' },
  { label: 'ICO Global (Mobile Satellite Service)', value: '+881 0' },
  { label: 'India', value: '+91' },
  { label: 'Indonesia', value: '+62' },
  { label: 'Inmarsat SNAC', value: '+870' },
  { label: 'International Freephone Service (UIFN)', value: '+800' },
  { label: 'International Networks', value: '+882' },
  { label: 'International Premium Rate Service’', value: '+979' },
  { label: 'International Shared Cost Service (ISCS)', value: '+808' },
  { label: 'Iran', value: '+98' },
  { label: 'Iraq', value: '+964' },
  { label: 'Ireland', value: '+353' },
  { label: 'Iridium (Mobile Satellite service)', value: '+8816' },
  { label: 'Isle of Man', value: '+441624' },
  { label: 'Israel', value: '+972' },
  { label: 'Italy', value: '+39' },
  { label: 'Jamaica', value: '+1 876' },
  { label: 'Jan Mayen', value: '+47 79' },
  { label: 'Japan', value: '+81' },
  { label: 'Jersey', value: '+441534' },
  { label: 'Jordan', value: '+962' },
  { label: 'Kazakhstan', value: '+76' },
  { label: 'Kenya', value: '+254' },
  { label: 'Kiribati', value: '+686' },
  { label: 'Korea, North', value: '+850' },
  { label: 'Korea, South', value: '+82' },
  { label: 'Kosovo', value: '+383' },
  { label: 'Kuwait', value: '+965' },
  { label: 'Kyrgyzstan', value: '+996' },
  { label: 'Laos', value: '+856' },
  { label: 'Latvia', value: '+371' },
  { label: 'Lebanon', value: '+961' },
  { label: 'Lesotho', value: '+266' },
  { label: 'Liberia', value: '+231' },
  { label: 'Libya', value: '+218' },
  { label: 'Liechtenstein', value: '+423' },
  { label: 'Lithuania', value: '+370' },
  { label: 'Luxembourg', value: '+352' },
  { label: 'Macau', value: '+853' },
  { label: 'Macedonia', value: '+389' },
  { label: 'Madagascar', value: '+261' },
  { label: 'Malawi', value: '+265' },
  { label: 'Malaysia', value: '+60' },
  { label: 'Maldives', value: '+960' },
  { label: 'Mali', value: '+223' },
  { label: 'Malta', value: '+356' },
  { label: 'Marshall Islands', value: '+692' },
  { label: 'Martinique', value: '+596' },
  { label: 'Mauritania', value: '+222' },
  { label: 'Mauritius', value: '+230' },
  { label: 'Mayotte', value: '+262 269' },
  { label: 'Mexico', value: '+52' },
  { label: 'Micronesia, Federated States of', value: '+691' },
  { label: 'Midway Island, USA', value: '+1 808' },
  { label: 'Moldova', value: '+373' },
  { label: 'Monaco', value: '+377' },
  { label: 'Mongolia', value: '+976' },
  { label: 'Montenegro', value: '+382' },
  { label: 'Montserrat', value: '+1 664' },
  { label: 'Morocco', value: '+212' },
  { label: 'Mozambique', value: '+258' },
  { label: 'Myanmar', value: '+95' },
  { label: 'Nagorno-Karabakh', value: '+374 47' },
  { label: 'Namibia', value: '+264' },
  { label: 'Nauru', value: '+674' },
  { label: 'Nepal', value: '+977' },
  { label: 'Netherlands', value: '+31' },
  { label: 'Nevis', value: '+1 869' },
  { label: 'New Caledonia', value: '+687' },
  { label: 'New Zealand', value: '+64' },
  { label: 'Nicaragua', value: '+505' },
  { label: 'Niger', value: '+227' },
  { label: 'Nigeria', value: '+234' },
  { label: 'Niue', value: '+683' },
  { label: 'Norfolk Island', value: '+672 3' },
  { label: 'Northern Cyprus', value: '+90 392' },
  { label: 'Northern Ireland', value: '+44 28' },
  { label: 'Northern Mariana Islands', value: '+1 670' },
  { label: 'Norway', value: '+47' },
  { label: 'Oman', value: '+968' },
  { label: 'Pakistan', value: '+92' },
  { label: 'Palau', value: '+680' },
  { label: 'Palestine, State of', value: '+970' },
  { label: 'Panama', value: '+507' },
  { label: 'Papua New Guinea', value: '+675' },
  { label: 'Paraguay', value: '+595' },
  { label: 'Peru', value: '+51' },
  { label: 'Philippines', value: '+63' },
  { label: 'Pitcairn Islands', value: '+64' },
  { label: 'Poland', value: '+48' },
  { label: 'Portugal', value: '+351' },
  { label: 'Puerto Rico', value: '+1 787' },
  { label: 'Qatar', value: '+974' },
  { label: 'Réunion', value: '+262' },
  { label: 'Romania', value: '+40' },
  { label: 'Russia', value: '+7' },
  { label: 'Rwanda', value: '+250' },
  { label: 'Saba', value: '+599 4' },
  { label: 'Saint Barthélemy', value: '+590' },
  { label: 'Saint Helena', value: '+290' },
  { label: 'Saint Kitts and Nevis', value: '+1 869' },
  { label: 'Saint Lucia', value: '+1 758' },
  { label: 'Saint Martin (France)', value: '+590' },
  { label: 'Saint Pierre and Miquelon', value: '+508' },
  { label: 'Saint Vincent and the Grenadines', value: '+1 784' },
  { label: 'Samoa', value: '+685' },
  { label: 'San Marino', value: '+378' },
  { label: 'São Tomé and Príncipe', value: '+239' },
  { label: 'Saudi Arabia', value: '+966' },
  { label: 'Senegal', value: '+221' },
  { label: 'Serbia', value: '+381' },
  { label: 'Seychelles', value: '+248' },
  { label: 'Sierra Leone', value: '+232' },
  { label: 'Singapore', value: '+65' },
  { label: 'Sint Eustatius', value: '+599 3' },
  { label: 'Sint Maarten (Netherlands)', value: '+1 721' },
  { label: 'Slovakia', value: '+421' },
  { label: 'Slovenia', value: '+386' },
  { label: 'Solomon Islands', value: '+677' },
  { label: 'Somalia', value: '+252' },
  { label: 'South Africa', value: '+27' },
  { label: 'South Georgia and the South Sandwich Islands', value: '+500' },
  { label: 'South Ossetia', value: '+995 34' },
  { label: 'South Sudan', value: '+211' },
  { label: 'Spain', value: '+34' },
  { label: 'Sri Lanka', value: '+94' },
  { label: 'Sudan', value: '+249' },
  { label: 'Suriname', value: '+597' },
  { label: 'Svalbard', value: '+47 79' },
  { label: 'Swaziland', value: '+268' },
  { label: 'Sweden', value: '+46' },
  { label: 'Switzerland', value: '+41' },
  { label: 'Syria', value: '+963' },
  { label: 'Taiwan', value: '+886' },
  { label: 'Tajikistan', value: '+992' },
  { label: 'Tanzania', value: '+255' },
  { label: 'Telecommunications for Disaster Relief by OCHA', value: '+888' },
  { label: 'Thailand', value: '+66' },
  { label: 'Thuraya (Mobile Satellite service)', value: '+882 16' },
  { label: 'Togo', value: '+228' },
  { label: 'Tokelau', value: '+690' },
  { label: 'Tonga', value: '+676' },
  { label: 'Transnistria', value: '+373 2' },
  { label: 'Trinidad and Tobago', value: '+1 868' },
  { label: 'Tristan da Cunha', value: '+290 8' },
  { label: 'Tunisia', value: '+216' },
  { label: 'Turkey', value: '+90' },
  { label: 'Turkmenistan', value: '+993' },
  { label: 'Turks and Caicos Islands', value: '+1 649' },
  { label: 'Tuvalu', value: '+688' },
  { label: 'Uganda', value: '+256' },
  { label: 'Ukraine', value: '+380' },
  { label: 'United Arab Emirates', value: '+971' },
  { label: 'United Kingdom', value: '+44' },
  { label: 'United States', value: '+1' },
  { label: 'Uruguay', value: '+598' },
  { label: 'US Virgin Islands', value: '+1340' },
  { label: 'Uzbekistan', value: '+998' },
  { label: 'Vanuatu', value: '+678' },
  { label: 'Venezuela', value: '+58' },
  { label: 'Vietnam', value: '+84' },
  { label: 'Wake Island, USA', value: '+1808' },
  { label: 'Wallis and Futuna', value: '+681' },
  { label: 'Yemen', value: '+967' },
  { label: 'Zambia', value: '+260' },
  { label: 'Zanzibar', value: '+25524' },
  { label: 'Zimbabwe', value: '+263' },
];

export const countriesList: Array<DropDownfieldsType> = [
  { label: 'Abkhazia', value: 'Abkhazia' },
  { label: 'Afghanistan', value: 'Afghanistan' },
  { label: 'Åland Islands', value: 'Åland Islands' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'American Samoa', value: 'American Samoa' },
  { label: 'Andorra', value: 'Andorra' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Anguilla', value: 'Anguilla' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Armenia', value: 'Armenia' },
  { label: 'Aruba', value: 'Aruba' },
  { label: 'Ascension', value: 'Ascension' },
  { label: 'Australia', value: 'Australia' },
  {
    label: 'Australian Antarctic Territory',
    value: 'Australian Antarctic Territory',
  },
  {
    label: 'Australian External Territories',
    value: 'Australian External Territories',
  },
  { label: 'Austria', value: 'Austria' },
  { label: 'Azerbaijan', value: 'Azerbaijan' },
  { label: 'Bahamas', value: 'Bahamas' },
  { label: 'Bahrain', value: 'Bahrain' },
  { label: 'Bangladesh', value: 'Bangladesh' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Barbuda', value: 'Barbuda' },
  { label: 'Belarus', value: 'Belarus' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Belize', value: 'Belize' },
  { label: 'Benin', value: 'Benin' },
  { label: 'Bermuda', value: 'Bermuda' },
  { label: 'Bhutan', value: 'Bhutan' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Bonaire', value: 'Bonaire' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'Brazil', value: 'Brazil' },
  {
    label: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  },
  { label: 'British Virgin Islands', value: 'British Virgin Islands' },
  { label: 'Brunei Darussalam', value: 'Brunei Darussalam' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Burundi', value: 'Burundi' },
  { label: 'Cambodia', value: 'Cambodia' },
  { label: 'Cameroon', value: 'Cameroon' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Cape Verde', value: 'Cape Verde' },
  { label: 'Caribbean Netherlands', value: 'Caribbean Netherlands' },
  { label: 'Cayman Islands', value: 'Cayman Islands' },
  { label: 'Central African Republic', value: 'Central African Republic' },
  { label: 'Chad', value: 'Chad' },
  {
    label: 'Chatham Island, New Zealand',
    value: 'Chatham Island, New Zealand',
  },
  { label: 'Chile', value: 'Chile' },
  { label: 'China', value: 'China' },
  { label: 'Christmas Island', value: 'Christmas Island' },
  { label: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Comoros', value: 'Comoros' },
  { label: 'Congo', value: 'Congo' },
  {
    label: 'Congo, the Democratic Republic of the (Zaire)',
    value: 'Congo, the Democratic Republic of the (Zaire)',
  },
  { label: 'Cook Islands', value: 'Cook Islands' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Ivory Coast', value: 'Ivory Coast' },
  { label: 'Croatia', value: 'Croatia' },
  { label: 'Cuba', value: 'Cuba' },
  { label: 'Guantanamo Bay, Cuba', value: 'Guantanamo Bay, Cuba' },
  { label: 'Curaçao', value: 'Curaçao' },
  { label: 'Cyprus', value: 'Cyprus' },
  { label: 'Czech Republic', value: 'Czech Republic' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Diego Garcia', value: 'Diego Garcia' },
  { label: 'Djibouti', value: 'Djibouti' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'Dominican Republic', value: 'Dominican Republic' },
  { label: 'East Timor', value: 'East Timor' },
  { label: 'Easter Island', value: 'Easter Island' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'El Salvador', value: 'El Salvador' },
  {
    label: 'Ellipso (Mobile Satellite service)',
    value: 'Ellipso (Mobile Satellite service)',
  },
  {
    label: 'EMSAT (Mobile Satellite service)',
    value: 'EMSAT (Mobile Satellite service)',
  },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { label: 'Eritrea', value: 'Eritrea' },
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Falkland Islands', value: 'Falkland Islands' },
  { label: 'Faroe Islands', value: 'Faroe Islands' },
  { label: 'Fiji', value: 'Fiji' },
  { label: 'Finland', value: 'Finland' },
  { label: 'France', value: 'France' },
  { label: 'French Antilles', value: 'French Antilles' },
  { label: 'French Guiana', value: 'French Guiana' },
  { label: 'French Polynesia', value: 'French Polynesia' },
  { label: 'Gabon', value: 'Gabon' },
  { label: 'Gambia', value: 'Gambia' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'Gibraltar', value: 'Gibraltar' },
  {
    label: 'Global Mobile Satellite System (GMSS)',
    value: 'Global Mobile Satellite System (GMSS)',
  },
  {
    label: 'Globalstar (Mobile Satellite Service)',
    value: 'Globalstar (Mobile Satellite Service)',
  },
  { label: 'Greece', value: 'Greece' },
  { label: 'Greenland', value: 'Greenland' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Guadeloupe', value: 'Guadeloupe' },
  { label: 'Guam', value: 'Guam' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Guernsey', value: 'Guernsey' },
  { label: 'Guinea', value: 'Guinea' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { label: 'Guyana', value: 'Guyana' },
  { label: 'Haiti', value: 'Haiti' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'Hong Kong', value: 'Hong Kong' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Iceland', value: 'Iceland' },
  {
    label: 'ICO Global (Mobile Satellite Service)',
    value: 'ICO Global (Mobile Satellite Service)',
  },
  { label: 'India', value: 'India' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Inmarsat SNAC', value: 'Inmarsat SNAC' },
  {
    label: 'International Freephone Service (UIFN)',
    value: 'International Freephone Service (UIFN)',
  },
  { label: 'International Networks', value: 'International Networks' },
  {
    label: 'International Premium Rate Service’',
    value: 'International Premium Rate Service’',
  },
  {
    label: 'International Shared Cost Service (ISCS)',
    value: 'International Shared Cost Service (ISCS)',
  },
  { label: 'Iran', value: 'Iran' },
  { label: 'Iraq', value: 'Iraq' },
  { label: 'Ireland', value: 'Ireland' },
  {
    label: 'Iridium (Mobile Satellite service)',
    value: 'Iridium (Mobile Satellite service)',
  },
  { label: 'Isle of Man', value: 'Isle of Man' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Jan Mayen', value: 'Jan Mayen' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Jersey', value: 'Jersey' },
  { label: 'Jordan', value: 'Jordan' },
  { label: 'Kazakhstan', value: 'Kazakhstan' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'Kiribati', value: 'Kiribati' },
  { label: 'Korea, North', value: 'Korea, North' },
  { label: 'Korea, South', value: 'Korea, South' },
  { label: 'Kosovo', value: 'Kosovo' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  { label: 'Laos', value: 'Laos' },
  { label: 'Latvia', value: 'Latvia' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Lesotho', value: 'Lesotho' },
  { label: 'Liberia', value: 'Liberia' },
  { label: 'Libya', value: 'Libya' },
  { label: 'Liechtenstein', value: 'Liechtenstein' },
  { label: 'Lithuania', value: 'Lithuania' },
  { label: 'Luxembourg', value: 'Luxembourg' },
  { label: 'Macau', value: 'Macau' },
  { label: 'Macedonia', value: 'Macedonia' },
  { label: 'Madagascar', value: 'Madagascar' },
  { label: 'Malawi', value: 'Malawi' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'Maldives', value: 'Maldives' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Marshall Islands', value: 'Marshall Islands' },
  { label: 'Martinique', value: 'Martinique' },
  { label: 'Mauritania', value: 'Mauritania' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Mayotte', value: 'Mayotte' },
  { label: 'Mexico', value: 'Mexico' },
  {
    label: 'Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
  },
  { label: 'Midway Island, USA', value: 'Midway Island, USA' },
  { label: 'Moldova', value: 'Moldova' },
  { label: 'Monaco', value: 'Monaco' },
  { label: 'Mongolia', value: 'Mongolia' },
  { label: 'Montenegro', value: 'Montenegro' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Myanmar', value: 'Myanmar' },
  { label: 'Nagorno-Karabakh', value: 'Nagorno-Karabakh' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Nauru', value: 'Nauru' },
  { label: 'Nepal', value: 'Nepal' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Nevis', value: 'Nevis' },
  { label: 'New Caledonia', value: 'New Caledonia' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Niue', value: 'Niue' },
  { label: 'Norfolk Island', value: 'Norfolk Island' },
  { label: 'Northern Cyprus', value: 'Northern Cyprus' },
  { label: 'Northern Ireland', value: 'Northern Ireland' },
  { label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Oman', value: 'Oman' },
  { label: 'Pakistan', value: 'Pakistan' },
  { label: 'Palau', value: 'Palau' },
  { label: 'Palestine, State of', value: 'Palestine, State of' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Pitcairn Islands', value: 'Pitcairn Islands' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Puerto Rico', value: 'Puerto Rico' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Réunion', value: 'Réunion' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Russia', value: 'Russia' },
  { label: 'Rwanda', value: 'Rwanda' },
  { label: 'Saba', value: 'Saba' },
  { label: 'Saint Barthélemy', value: 'Saint Barthélemy' },
  { label: 'Saint Helena', value: 'Saint Helena' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
  { label: 'Saint Lucia', value: 'Saint Lucia' },
  { label: 'Saint Martin (France)', value: 'Saint Martin (France)' },
  { label: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon' },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  { label: 'Samoa', value: 'Samoa' },
  { label: 'San Marino', value: 'San Marino' },
  { label: 'São Tomé and Príncipe', value: 'São Tomé and Príncipe' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Serbia', value: 'Serbia' },
  { label: 'Seychelles', value: 'Seychelles' },
  { label: 'Sierra Leone', value: 'Sierra Leone' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Sint Eustatius', value: 'Sint Eustatius' },
  { label: 'Sint Maarten (Netherlands)', value: 'Sint Maarten (Netherlands)' },
  { label: 'Slovakia', value: 'Slovakia' },
  { label: 'Slovenia', value: 'Slovenia' },
  { label: 'Solomon Islands', value: 'Solomon Islands' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'South Africa', value: 'South Africa' },
  {
    label: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
  },
  { label: 'South Ossetia', value: 'South Ossetia' },
  { label: 'South Sudan', value: 'South Sudan' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Sri Lanka', value: 'Sri Lanka' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Suriname', value: 'Suriname' },
  { label: 'Svalbard', value: 'Svalbard' },
  { label: 'Swaziland', value: 'Swaziland' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Syria', value: 'Syria' },
  { label: 'Taiwan', value: 'Taiwan' },
  { label: 'Tajikistan', value: 'Tajikistan' },
  { label: 'Tanzania', value: 'Tanzania' },
  {
    label: 'Telecommunications for Disaster Relief by OCHA',
    value: 'Telecommunications for Disaster Relief by OCHA',
  },
  { label: 'Thailand', value: 'Thailand' },
  {
    label: 'Thuraya (Mobile Satellite service)',
    value: 'Thuraya (Mobile Satellite service)',
  },
  { label: 'Togo', value: 'Togo' },
  { label: 'Tokelau', value: 'Tokelau' },
  { label: 'Tonga', value: 'Tonga' },
  { label: 'Transnistria', value: 'Transnistria' },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { label: 'Tristan da Cunha', value: 'Tristan da Cunha' },
  { label: 'Tunisia', value: 'Tunisia' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Turkmenistan', value: 'Turkmenistan' },
  { label: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
  { label: 'Tuvalu', value: 'Tuvalu' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Ukraine', value: 'Ukraine' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'US Virgin Islands', value: 'US Virgin Islands' },
  { label: 'Uzbekistan', value: 'Uzbekistan' },
  { label: 'Vanuatu', value: 'Vanuatu' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'Wake Island, USA', value: 'Wake Island, USA' },
  { label: 'Wallis and Futuna', value: 'Wallis and Futuna' },
  { label: 'Yemen', value: 'Yemen' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Zanzibar', value: 'Zanzibar' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
];

export const timeSlotsStart: Array<DropDownfieldsType> = [
  { label: '00:00', value: '00:00' },
  { label: '00:15', value: '00:15' },
  { label: '00:30', value: '00:30' },
  { label: '00:45', value: '00:45' },
  { label: '01:00', value: '01:00' },
  { label: '01:15', value: '01:15' },
  { label: '01:30', value: '01:30' },
  { label: '01:45', value: '01:45' },
  { label: '02:00', value: '02:00' },
  { label: '02:15', value: '02:15' },
  { label: '02:30', value: '02:30' },
  { label: '02:45', value: '02:45' },
  { label: '03:00', value: '03:00' },
  { label: '03:15', value: '03:15' },
  { label: '03:30', value: '03:30' },
  { label: '03:45', value: '03:45' },
  { label: '04:00', value: '04:00' },
  { label: '04:15', value: '04:15' },
  { label: '04:30', value: '04:30' },
  { label: '04:45', value: '04:45' },
  { label: '05:00', value: '05:00' },
  { label: '05:15', value: '05:15' },
  { label: '05:30', value: '05:30' },
  { label: '05:45', value: '05:45' },
  { label: '06:00', value: '06:00' },
  { label: '06:15', value: '06:15' },
  { label: '06:30', value: '06:30' },
  { label: '06:45', value: '06:45' },
  { label: '07:00', value: '07:00' },
  { label: '07:15', value: '07:15' },
  { label: '07:30', value: '07:30' },
  { label: '07:45', value: '07:45' },
  { label: '08:00', value: '08:00' },
  { label: '08:15', value: '08:15' },
  { label: '08:30', value: '08:30' },
  { label: '08:45', value: '08:45' },
  { label: '09:00', value: '09:00' },
  { label: '09:15', value: '09:15' },
  { label: '09:30', value: '09:30' },
  { label: '09:45', value: '09:45' },
  { label: '10:00', value: '10:00' },
  { label: '10:15', value: '10:15' },
  { label: '10:30', value: '10:30' },
  { label: '10:45', value: '10:45' },
  { label: '11:00', value: '11:00' },
  { label: '11:15', value: '11:15' },
  { label: '11:30', value: '11:30' },
  { label: '11:45', value: '11:45' },
  { label: '12:00', value: '12:00' },
  { label: '12:15', value: '12:15' },
  { label: '12:30', value: '12:30' },
  { label: '12:45', value: '12:45' },
  { label: '13:00', value: '13:00' },
  { label: '13:15', value: '13:15' },
  { label: '13:30', value: '13:30' },
  { label: '13:45', value: '13:45' },
  { label: '14:00', value: '14:00' },
  { label: '14:15', value: '14:15' },
  { label: '14:30', value: '14:30' },
  { label: '14:45', value: '14:45' },
  { label: '15:00', value: '15:00' },
  { label: '15:15', value: '15:15' },
  { label: '15:30', value: '15:30' },
  { label: '15:45', value: '15:45' },
  { label: '16:00', value: '16:00' },
  { label: '16:15', value: '16:15' },
  { label: '16:30', value: '16:30' },
  { label: '16:45', value: '16:45' },
  { label: '17:00', value: '17:00' },
  { label: '17:15', value: '17:15' },
  { label: '17:30', value: '17:30' },
  { label: '17:45', value: '17:45' },
  { label: '18:00', value: '18:00' },
  { label: '18:15', value: '18:15' },
  { label: '18:30', value: '18:30' },
  { label: '18:45', value: '18:45' },
  { label: '19:00', value: '19:00' },
  { label: '19:15', value: '19:15' },
  { label: '19:30', value: '19:30' },
  { label: '19:45', value: '19:45' },
  { label: '20:00', value: '20:00' },
  { label: '20:15', value: '20:15' },
  { label: '20:30', value: '20:30' },
  { label: '20:45', value: '20:45' },
  { label: '21:00', value: '21:00' },
  { label: '21:15', value: '21:15' },
  { label: '21:30', value: '21:30' },
  { label: '21:45', value: '21:45' },
  { label: '22:00', value: '22:00' },
  { label: '22:15', value: '22:15' },
  { label: '22:30', value: '22:30' },
  { label: '22:45', value: '22:45' },
  { label: '23:00', value: '23:00' },
  { label: '23:15', value: '23:15' },
  { label: '23:30', value: '23:30' },
  { label: '23:45', value: '23:45' },
];

export const timeSlotsEnd: Array<DropDownfieldsType> = [
  { label: '00:15', value: '00:15' },
  { label: '00:30', value: '00:30' },
  { label: '00:45', value: '00:45' },
  { label: '01:00', value: '01:00' },
  { label: '01:15', value: '01:15' },
  { label: '01:30', value: '01:30' },
  { label: '01:45', value: '01:45' },
  { label: '02:00', value: '02:00' },
  { label: '02:15', value: '02:15' },
  { label: '02:30', value: '02:30' },
  { label: '02:45', value: '02:45' },
  { label: '03:00', value: '03:00' },
  { label: '03:15', value: '03:15' },
  { label: '03:30', value: '03:30' },
  { label: '03:45', value: '03:45' },
  { label: '04:00', value: '04:00' },
  { label: '04:15', value: '04:15' },
  { label: '04:30', value: '04:30' },
  { label: '04:45', value: '04:45' },
  { label: '05:00', value: '05:00' },
  { label: '05:15', value: '05:15' },
  { label: '05:30', value: '05:30' },
  { label: '05:45', value: '05:45' },
  { label: '06:00', value: '06:00' },
  { label: '06:15', value: '06:15' },
  { label: '06:30', value: '06:30' },
  { label: '06:45', value: '06:45' },
  { label: '07:00', value: '07:00' },
  { label: '07:15', value: '07:15' },
  { label: '07:30', value: '07:30' },
  { label: '07:45', value: '07:45' },
  { label: '08:00', value: '08:00' },
  { label: '08:15', value: '08:15' },
  { label: '08:30', value: '08:30' },
  { label: '08:45', value: '08:45' },
  { label: '09:00', value: '09:00' },
  { label: '09:15', value: '09:15' },
  { label: '09:30', value: '09:30' },
  { label: '09:45', value: '09:45' },
  { label: '10:00', value: '10:00' },
  { label: '10:15', value: '10:15' },
  { label: '10:30', value: '10:30' },
  { label: '10:45', value: '10:45' },
  { label: '11:00', value: '11:00' },
  { label: '11:15', value: '11:15' },
  { label: '11:30', value: '11:30' },
  { label: '11:45', value: '11:45' },
  { label: '12:00', value: '12:00' },
  { label: '12:15', value: '12:15' },
  { label: '12:30', value: '12:30' },
  { label: '12:45', value: '12:45' },
  { label: '13:00', value: '13:00' },
  { label: '13:15', value: '13:15' },
  { label: '13:30', value: '13:30' },
  { label: '13:45', value: '13:45' },
  { label: '14:00', value: '14:00' },
  { label: '14:15', value: '14:15' },
  { label: '14:30', value: '14:30' },
  { label: '14:45', value: '14:45' },
  { label: '15:00', value: '15:00' },
  { label: '15:15', value: '15:15' },
  { label: '15:30', value: '15:30' },
  { label: '15:45', value: '15:45' },
  { label: '16:00', value: '16:00' },
  { label: '16:15', value: '16:15' },
  { label: '16:30', value: '16:30' },
  { label: '16:45', value: '16:45' },
  { label: '17:00', value: '17:00' },
  { label: '17:15', value: '17:15' },
  { label: '17:30', value: '17:30' },
  { label: '17:45', value: '17:45' },
  { label: '18:00', value: '18:00' },
  { label: '18:15', value: '18:15' },
  { label: '18:30', value: '18:30' },
  { label: '18:45', value: '18:45' },
  { label: '19:00', value: '19:00' },
  { label: '19:15', value: '19:15' },
  { label: '19:30', value: '19:30' },
  { label: '19:45', value: '19:45' },
  { label: '20:00', value: '20:00' },
  { label: '20:15', value: '20:15' },
  { label: '20:30', value: '20:30' },
  { label: '20:45', value: '20:45' },
  { label: '21:00', value: '21:00' },
  { label: '21:15', value: '21:15' },
  { label: '21:30', value: '21:30' },
  { label: '21:45', value: '21:45' },
  { label: '22:00', value: '22:00' },
  { label: '22:15', value: '22:15' },
  { label: '22:30', value: '22:30' },
  { label: '22:45', value: '22:45' },
  { label: '23:00', value: '23:00' },
  { label: '23:15', value: '23:15' },
  { label: '23:30', value: '23:30' },
  { label: '23:45', value: '23:45' },
  { label: '00:00', value: '00:00' },
];

export const courierList: Array<DropDownfieldsType> = [
  { label: 'UPS', value: 'ups' },
  { label: 'FedEx', value: 'fedex' },
];
